# Generated by Django 4.0 on 2021-12-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapi',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
