# Generated by Django 4.0 on 2021-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapi',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user')], default='USER', max_length=100),
        ),
    ]
